#!/bin/bash

xset -dpms
xset s off
xset s noblank
#openbox-session &

function prettify()
{
	while [ -z $wid ]; do
		sleep 1;
		wid=$(xdotool search --onlyvisible --name firefox)
	done
	xdotool windowmove $wid 0 0 
	xdotool windowsize $wid 100% 100% 
}

prettify &
firefox-esr  "http://youtube.com" 
#chromium-browser --no-first-run "http://google.com"
#chromium-browser --kiosk --no-first-run "http://localhost:3000"
